export const
    ALTERA_EMPRESA = 'ALTERA_EMPRESA',
    EMPRESA_POR_ID = 'EMPRESA_POR_ID',
    TODAS_EMPRESAS = 'TODAS_EMPRESAS',
    LIMPAR_EMPRESA_POR_ID = 'LIMPAR_EMPRESA_POR_ID',
    LIMPAR_EMPRESAS = 'LIMPAR_EMPRESAS';