export const
    ALTERA_EMPRESA = 'ALTERA_EMPRESA',
    TODAS_EMPRESAS = 'TODAS_EMPRESAS',
    UMA_EMPRESA = 'UMA_EMPRESA',
    LIMPAR_EMPRESA = 'LIMPAR_EMPRESA',
    LIMPAR_EMPRESAS = 'LIMPAR_EMPRESAS';