export const
    BUSCAR_USUARIO = 'BUSCAR_USUARIO',
    LIMPAR_USUARIO = 'LIMPAR_USUARIO',
    LIMPAR_USUARIOS = 'LIMPAR_USUARIOS',
    LISTAR_USUARIOS = 'LISTAR_USUARIOS',
    LOGIN_USUARIO = 'LOGIN_USUARIO',
    LOGOUT_USUARIO = 'LOGOUT_USUARIO',
    PESQUISAR_USUARIOS = 'PESQUISAR_USUARIOS';